pipeline{
	
	agent any
	
	stages{
		
		stage('stage-1'){
			steps{
				echo "doing mvn clean"
				echo "doing mvn package"
			}
		}
		
		stage('stage-2'){
			steps{
				echo "builiding docker image"
			}
		}
		
		stage('stage-3'){
			steps{
				echo "pushing docker image"
				echo "execute docker image"
			}
		}
	}
	post{
		always{
			echo "docker pipleline execution is completed"
		}
	}
}